---
- name: Ensure PHP packages are installed.
  package:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
    enablerepo: "{{ php_enablerepo }}"
  with_items: "{{ php_packages }}"
  notify: restart webserver

- name: Setting up SELinux booleans
  seboolean: name={{ item }} state=yes persistent=yes
  with_items:
  - httpd_can_network_connect
